# azure-pipelines.yml

trigger:
  - main  # or master, depending on your branch

pool:
  vmImage: 'windows-latest'  # use 'ubuntu-latest' for Linux

steps:
  - task: Checkout@1
    displayName: 'Checkout code'

  - script: echo Hello, Azure DevOps Pipeline!
    displayName: 'Run a simple test script'

  - script: |
      echo Running additional tasks...
      dir
    displayName: 'List files in workspace'
