trigger:
  branches:
    include:
      - main

variables:
  azureContainerRegistry: <youracr>.azurecr.io
  backendImageName: youtube-backend
  frontendImageName: youtube-frontend
  kubernetesNamespace: youtube-clone

stages:
- stage: BuildAndPush
  displayName: Build and Push Docker Images
  jobs:
  - job: DockerBuild
    displayName: Build and Push
    pool: myagent
    steps:
    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: '<ACR-SERVICE-CONNECTION>'

    - task: Docker@2
      displayName: Build and Push Backend
      inputs:
        command: buildAndPush
        repository: $(backendImageName)
        dockerfile: backend/Dockerfile
        containerRegistry: '<ACR-SERVICE-CONNECTION>'
        tags: latest

    - task: Docker@2
      displayName: Build and Push Frontend
      inputs:
        command: buildAndPush
        repository: $(frontendImageName)
        dockerfile: frontend/Dockerfile
        containerRegistry: '<ACR-SERVICE-CONNECTION>'
        tags: latest

- stage: Deploy
  displayName: Deploy to AKS
  dependsOn: BuildAndPush
  jobs:
  - job: DeployToAKS
    displayName: Apply K8s YAML
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Kubernetes@1
      displayName: Set K8s Context
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscription: '<AZURE-RM-SERVICE-CONNECTION>'
        azureResourceGroup: '<YOUR-RESOURCE-GROUP>'
        kubernetesCluster: '<YOUR-AKS-CLUSTER>'
        namespace: $(kubernetesNamespace)
        command: apply
        useConfigurationFile: true
        configuration: 'k8s/youtube-app.yaml'
