# azure-pipelines.yml

trigger:
  - main  # Make sure this matches your actual branch name

pool:
  vmImage: 'windows-latest'  # Or 'ubuntu-latest' for Linux

steps:
  - checkout: self  # Correct way to checkout code

  - script: echo "Hello, Azure DevOps!"
    displayName: 'Say Hello'
