trigger:
  branches:
    include:
      - main

pool: myagent

variables:
  imageName: uttam198/docker
  imageTag: latest
  kubernetesNamespace: default

stages:
- stage: BuildAndPush
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    steps:
    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        command: login
        containerRegistry: 'DockerHubConnection'  # Created in Service Connections

    - task: Docker@2
      displayName: Build and Push Image
      inputs:
        command: buildAndPush
        containerRegistry: 'DockerHubConnection'
        repository: $(imageName)
        dockerfile: Dockerfile
        tags: |
          $(imageTag)

- stage: Deploy
  displayName: Deploy to AKS
  dependsOn: BuildAndPush
  jobs:
  - job: DeployToAKS
    steps:
    - task: Kubernetes@1
      displayName: Deploy App to AKS
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: 'AzureRM-DevOp'
        azureResourceGroup: 'Raj'
        kubernetesCluster: 'aks'
        namespace: default
        command: apply
        useConfigurationFile: true
        configuration: custom-app.yaml
