trigger:
  branches:
    include:
      - main

variables:
  nodeVersion: '22.17.0'
  dotnetVersion: '8.0.412'
  deployRoot: '\\MyServer\DeployShare'

stages:

# 1️⃣ Build Frontend
- stage: Build_Frontend
  displayName: Build Frontend
  jobs:
    - job: BuildReactApp
      pool:
        name: 'Myagent'
      steps:
        - checkout: self

        # Debug Repo
        - powershell: |
            Write-Host "=== REPO CONTENTS ==="
            Get-ChildItem -Path "$(Build.SourcesDirectory)" -Recurse
          displayName: 'Debug: Show Repo Contents'

        - task: NodeTool@0
          inputs:
            versionSpec: $(nodeVersion)
          displayName: 'Use Node.js $(nodeVersion)'

        - script: |
            npm install
            npm run build
          workingDirectory: '$(Build.SourcesDirectory)/frontend'
          displayName: 'Install and Build Frontend'

        # Debug Frontend Output
        - powershell: |
            if (Test-Path "$(Build.SourcesDirectory)\frontend\build") {
              Write-Host "Build folder exists."
              Get-ChildItem -Path "$(Build.SourcesDirectory)\frontend\build" -Recurse
            } else {
              Write-Error "Frontend build folder does not exist!"
            }
          displayName: 'Debug: Check Frontend Build Folder'
          continueOnError: true

        # ✅ Copy frontend build output to file share
        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(Build.SourcesDirectory)/frontend/build'
            Contents: '**'
            TargetFolder: '$(deployRoot)\frontend'
          displayName: 'Deploy Frontend to File Share'


# 2️⃣ Build Backend
- stage: Build_Backend
  displayName: Build Backend
  jobs:
    - job: BuildBackend
      pool:
        name: 'Myagent'
      steps:
        - checkout: self

        # Use .NET
        - task: UseDotNet@2
          inputs:
            packageType: 'sdk'
            version: $(dotnetVersion)
          displayName: 'Use .NET $(dotnetVersion)'

        # Build and publish backend
        - script: |
            dotnet restore
            dotnet build --configuration Release
            dotnet publish -c Release -o $(Build.SourcesDirectory)/Backend/publish
          workingDirectory: '$(Build.SourcesDirectory)/Backend/MyApiProject'
          displayName: 'Build and Publish Backend'

        # Debug Backend Output
        - powershell: |
            if (Test-Path "$(Build.SourcesDirectory)\Backend\publish") {
              Write-Host "Publish folder exists."
              Get-ChildItem -Path "$(Build.SourcesDirectory)\Backend\publish" -Recurse
            } else {
              Write-Error "Backend publish folder does not exist!"
            }
          displayName: 'Debug: Check Backend Publish Folder'
          continueOnError: true

        # ✅ Copy backend publish output to file share
        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(Build.SourcesDirectory)/Backend/publish'
            Contents: '**'
            TargetFolder: '$(deployRoot)\backend'
          displayName: 'Deploy Backend to File Share'
